# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "storybook"

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        # Set up Node
      - uses: actions/setup-node@v4
        with:
         node-version: '20.x'

      - name: Print Folder
        run: |
          echo "list" >> 
          ls

      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: ../storybook-static
          install_command: npm ci
          build_command: npm run build-storybook


